name:               "Hugo Build"
author:             Benjamin Becker
description:        "Perform a hugo build"
branding:
  icon:             arrow-right
  color:            purple

runs:
  using:            'docker'
  image:            'docker://blbecker/hugo-build:latest'

inputs:
  hugo_args:
    description:    "Additional arguments to pass to hugo"
    required:       false

